== Using Shared Data with Vert.x

Shared data contains functionality that allows you to safely share data between different parts of your application,
or different applications in the same Vert.x instance or across a cluster of Vert.x instances.

Shared data provides:

 * synchronous shared maps (local)
 * asynchronous maps (local or cluster-wide)
 * asynchronous locks (local or cluster-wide)
 * asynchronous counters (local or cluster-wide)

IMPORTANT: The behavior of the distributed data structure depends on the cluster manager you use. Backup
(replication) and behavior when a network partition is faced are defined by the cluster manager and its
configuration. Refer to the cluster manager documentation as well as to the underlying framework manual.

=== Local shared maps

`link:../../jsdoc/module-vertx-js_local_map-LocalMap.html[Local shared maps]` allow you to share data safely between different event
loops (e.g. different verticles) in the same Vert.x instance.

Local shared maps only allow certain data types to be used as keys and values. Those types must either be immutable,
or certain other types that can be copied like `link:../../jsdoc/module-vertx-js_buffer-Buffer.html[Buffer]`. In the latter case the key/value
will be copied before putting it in the map.

This way we can ensure there is no _shared access to mutable state_ between different threads in your Vert.x application
so you don't have to worry about protecting that state by synchronising access to it.

Here's an example of using a shared local map:

[source,js]
----
var Buffer = require("vertx-js/buffer");

var sd = vertx.sharedData();

var map1 = sd.getLocalMap("mymap1");

map1.put("foo", "bar");

var map2 = sd.getLocalMap("mymap2");

map2.put("eek", Buffer.buffer().appendInt(123));

// Then... in another part of your application:

map1 = sd.getLocalMap("mymap1");

var val = map1.get("foo");

map2 = sd.getLocalMap("mymap2");

var buff = map2.get("eek");

----

=== Asynchronous shared maps

Asynchronous shared maps allow data to be put in the map and retrieved locally when Vert.x is not clustered.
When clustered, data can be put from any node and retrieved from the same node or any other node.

IMPORTANT: In clustered mode, asynchronous shared maps rely on distributed data structures provided by the cluster manager.
Beware that the latency relative to asynchronous shared map operations can be much higher in clustered than in local mode.

This makes them really useful for things like storing session state in a farm of servers hosting a Vert.x web
application.

You get an instance of `link:../../jsdoc/module-vertx-js_async_map-AsyncMap.html[AsyncMap]` with
`link:../../jsdoc/module-vertx-js_shared_data-SharedData.html#getAsyncMap[getAsyncMap]`.

Getting the map is asynchronous and the result is returned to you in the handler that you specify. Here's an example:

[source,js]
----

var sd = vertx.sharedData();

sd.getAsyncMap("mymap", function (res, res_err) {
  if (res_err == null) {
    var map = res;
  } else {
    // Something went wrong!
  }
});


----

==== Putting data in a map

You put data in a map with `link:../../jsdoc/module-vertx-js_async_map-AsyncMap.html#put[put]`.

The actual put is asynchronous and the handler is notified once it is complete:

[source,js]
----

map.put("foo", "bar", function (resPut, resPut_err) {
  if (resPut_err == null) {
    // Successfully put the value
  } else {
    // Something went wrong!
  }
});


----

==== Getting data from a map

You get data from a map with `link:../../jsdoc/module-vertx-js_async_map-AsyncMap.html#get[get]`.

The actual get is asynchronous and the handler is notified with the result some time later

[source,js]
----

map.get("foo", function (resGet, resGet_err) {
  if (resGet_err == null) {
    // Successfully got the value
    var val = resGet;
  } else {
    // Something went wrong!
  }
});


----

===== Other map operations

You can also remove entries from an asynchronous map, clear them and get the size.

See the `link:../../jsdoc/module-vertx-js_async_map-AsyncMap.html[API docs]` for more information.

=== Asynchronous locks

`link:../../jsdoc/module-vertx-js_lock-Lock.html[Asynchronous locks]` allow you to obtain exclusive locks locally or across the cluster -
this is useful when you want to do something or access a resource on only one node of a cluster at any one time.

Asynchronous locks have an asynchronous API unlike most lock APIs which block the calling thread until the lock
is obtained.

To obtain a lock use `link:../../jsdoc/module-vertx-js_shared_data-SharedData.html#getLock[getLock]`.

This won't block, but when the lock is available, the handler will be called with an instance of `link:../../jsdoc/module-vertx-js_lock-Lock.html[Lock]`,
signifying that you now own the lock.

While you own the lock no other caller, anywhere on the cluster will be able to obtain the lock.

When you've finished with the lock, you call `link:../../jsdoc/module-vertx-js_lock-Lock.html#release[release]` to release it, so
another caller can obtain it.

[source,js]
----
sd.getLock("mylock", function (res, res_err) {
  if (res_err == null) {
    // Got the lock!
    var lock = res;

    // 5 seconds later we release the lock so someone else can get it

    vertx.setTimer(5000, function (tid) {
      lock.release();
    });

  } else {
    // Something went wrong
  }
});

----

You can also get a lock with a timeout. If it fails to obtain the lock within the timeout the handler will be called
with a failure:

[source,js]
----
sd.getLockWithTimeout("mylock", 10000, function (res, res_err) {
  if (res_err == null) {
    // Got the lock!
    var lock = res;

  } else {
    // Failed to get lock
  }
});

----

=== Asynchronous counters

It's often useful to maintain an atomic counter locally or across the different nodes of your application.

You can do this with `link:../../jsdoc/module-vertx-js_counter-Counter.html[Counter]`.

You obtain an instance with `link:../../jsdoc/module-vertx-js_shared_data-SharedData.html#getCounter[getCounter]`:

[source,js]
----
sd.getCounter("mycounter", function (res, res_err) {
  if (res_err == null) {
    var counter = res;
  } else {
    // Something went wrong!
  }
});

----

Once you have an instance you can retrieve the current count, atomically increment it, decrement and add a value to
it using the various methods.

See the `link:../../jsdoc/module-vertx-js_counter-Counter.html[API docs]` for more information.